/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    application
    kotlin("jvm") version "1.6.10"
}

repositories {
    maven {
        url = uri("https://m2.dv8tion.net/releases")
        content {
            includeGroup("net.dv8tion")
        }
    }

    maven {
        url = uri("https://jenkins.chew.pw/plugin/repository/everything/")
        content {
            includeGroup("me.memerator.api")
            includeGroup("pro.chew.api")
        }
    }

    maven {
        url = uri("https://m2.chew.pro/releases")
        content {
            includeGroup("pw.chew")
        }
    }

    mavenCentral()
}

dependencies {
    implementation("net.dv8tion", "JDA", "4.4.0_352")
    implementation("pw.chew", "jda-chewtils", "1.24.1")
    implementation("ch.qos.logback", "logback-classic", "1.2.10")
    implementation("com.squareup.okhttp3", "okhttp", "4.9.3")
    implementation("org.json", "json", "20211205")
    implementation("io.sentry", "sentry", "5.6.0")
    implementation("org.kohsuke", "github-api", "1.301")
    implementation("org.jsoup", "jsoup", "1.14.3")
    implementation("pro.chew.api", "ChewAPI", "1.0-b5")
    implementation("org.reflections", "reflections", "0.10.2")
    implementation("me.memerator.api", "MemeratorAPI", "1.1.0_70")
    implementation("org.hibernate", "hibernate-core", "5.6.5.Final")
    implementation("mysql", "mysql-connector-java", "8.0.28")
    implementation("org.codehaus.groovy", "groovy", "3.0.9")
    implementation("org.knowm.xchart", "xchart", "3.8.1")
}

group = "pw.chew.chewbotcca"
version = "2.0-SNAPSHOT"
description = "Chewbotcca"
java.sourceCompatibility = JavaVersion.VERSION_17

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        groupId = project.group.toString()
        artifactId = "Chewbotcca"
        version = project.version.toString()

        from(components["java"])
    }

    repositories {
        maven {
            url = uri("https://m2.chew.pro/snapshots")
            credentials {
                username = properties["mchew-username"].toString()
                password = properties["mchew-password"].toString()
            }
        }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>() {
    kotlinOptions.jvmTarget = "17"
    kotlinOptions.apiVersion = "1.6"
}

application {
    mainClass.set("pw.chew.chewbotcca.Chewbotcca")
}
