name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Compile

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Set up JDK
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
      with:
        java-version: 21
        distribution: 'zulu'
        cache: 'gradle'
    - name: Compile
      run: ./gradlew build
