name: Build

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Compile

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Compile
      run: mvn clean package
